### ISSUE TITLE
MethodAsync returns wrong type 

### ISSUE THREAD

**Issue by FredVmz** [dderevjanik/wsdl-tsclient#10]
Hello, 

I had a generated method initiateSsoSessionAsync, returning a promise of InitiateSsoSessionResponse : 

```initiateSsoSessionAsync(initiateSsoSessionRequest: InitiateSsoSessionRequest): Promise<InitiateSsoSessionResponse>;```

This InitiateSsoSessionResponse type is described below :

``` 
export interface InitiateSsoSessionResponse {
    /** ssoSessionIdType|tns:mandatoryStringType|pattern */
    ssoSessionId?: string;
};
```

So, when I called my method below, I was waiting for the response to be a InitiateSsoSessionResponse ( containing only a ssoSessionId attribute ) : 

```
return client.initiateSsoSessionAsync(initiateSsoSessionRequest).then((response: InitiateSsoSessionResponse) => {  
        console.log(response);
        console.log("response.ssoSessionId = " + response.ssoSessionId);
})
```
But trying to retrieve ssoSessionId, I've got undefined. But it's normal in someways, I have got what node soap returns normally : 

https://github.com/vpulim/node-soap#clientmethodasyncargs-options---call-method-on-the-soap-service

```
client.MyFunctionAsync({name: 'value'}).then((result) => {
    // result is a javascript array containing result, rawResponse, soapheader, and rawRequest
    // result is a javascript object
    // rawResponse is the raw xml response string
    // soapHeader is the response soap header as a javascript object
    // rawRequest is the raw xml request string
  })
```

The soap endpoint works, I retrieve data that I expected, but it's really confusing as the response typescript type is not the same as the node soap returned type... 

What do you think about it ? 

Thanks you very much in advance ! 

Frederic

**Comment by dderevjanik** [comment]
Hi FredVmz,

thank you for reporting an issue with wsdl-tsclient. I'm going to look into it. 
Could you provide example WSDL file, please ?

**Comment by FredVmz** [comment]
Exactly, and what we would like to have is a Promise of the object returned by the api, containing InitiateSsoSessionResponse as result, rawResponse, soapHeader and rawRequest

**Comment by dderevjanik** [comment]
Sure ! Will fix it later today and publish it to npm :)

**Comment by FredVmz** [comment]
Great, thank you ! :)

**Comment by dderevjanik** [comment]
I released new patched version https://github.com/dderevjanik/wsdl-tsclient/releases/tag/1.1.1 ,
please try and tell me if everything works as expected :)

**Comment by FredVmz** [comment]
Hi ! It works very well ! You have been very reactive, it's great !  Thank you !

**Comment by dderevjanik** [comment]
You're welcome :)
