### ISSUE TITLE
The name of the wrapping structures are converted to camelCase

### ISSUE THREAD

**Issue by zengatsu** [dderevjanik/wsdl-tsclient#15]
for example CreateUserRQ becomes createUserRq. the service I'm trying to use doesn't accept these.

**Comment by devyourcar** [comment]
I am facing this issue too - any chance we can pass a flag / turn off auto camelcasing via cli opts?

**Comment by dderevjanik** [comment]
Hi @zengatsu  and @devyourcar ,
could you please give me more information about this problem ? 

With camelcased name of wrapping structures - do you mean `Service`, `Port` or `Definition` ?

**Comment by zengatsu** [comment]
I'm sorry I didn't what the appropriate term is.
But I think it's a definition

This is request example:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope>
  <SOAP-ENV:Body>
    <ns1:createUser>
      <CreateUserRQ>
        ....
      </CreateUserRQ>
    </ns1:createUser>
```

So the issue is that CreateUserRQ with the camelCase becomes createUserRq which is not accepted by the webservice

My work around was to remove all usage of the camelCase package in the codebase. so I agree that adding a flag to disable it is a good idea.

**Comment by dderevjanik** [comment]
Will look into it definetly, thank you !

Also, I provide option for disabling camelCase at all :)

**Comment by devyourcar** [comment]
@dderevjanik - thanks! I ended up doing the same as zengatsu. Replaced all camelCase calls in wsdl-client so that the definitions match the casing from the wsdl source.

**Comment by devyourcar** [comment]
Instead of calling camelCase, I created a helper function (changeCase) and swapped all usage in-code.

```
import camelcase from "camelcase";

export default function changeCase(input: string, options?: camelcase.Options) {
    if (!options?.pascalCase) {
        return `${input.replace(/\./g, "")}`;
    }
    return camelcase(input, options);
}
```

**Comment by dderevjanik** [comment]
Looks great !
Would like to create PR ? You could move `./src/change-case.ts` to `./src/utils/change-case.ts`....

**Comment by aesweeting** [comment]
So it turns out I also needed this! I just raised #17 containing:

- The fix originally raised by @devyourcar (thanks!)
- A type fix to account for sequences of length 1 which don't get returned as arrays
    - I.e. `Array<MyType>` ➡️  `Array<MyType> | MyType`

**Comment by aesweeting** [comment]
Minor update - I removed the other fix from my PR
