### ISSUE TITLE
Support `overwrite`

### ISSUE THREAD

**Issue by cobraz** [dderevjanik/wsdl-tsclient#2]
It might be useful for some users (like myself) to override generated files, as such `wsdl-tsclient` can be used to generate files automatically even if they exist (e.g. in CI/CD workflow).

`ts-morph` supports this behavior natively. You have to pass `overwrite: true` in order to activate it.

AFAIK, the option needs to be added to the API/CLI, and passed to this:

https://github.com/dderevjanik/wsdl-tsclient/blob/aa3ec29da3a0a455156635044fae8222a0abc238/src/index.ts#L259

e.g.:

```typescript
const portFile = project.createSourceFile(portFilePath, "", { overwrite: true }); 
```

Would you be interested in a pull request on this?

### Related errors

- `Did you mean to provide the overwrite option? A source file already exists at the provided file path`

### Workaround

Before running `wsdl-tsclient`, delete your folder containing the files `wsdl-tsclient` has generated (e.g. `generated`).

**Comment by dderevjanik** [comment]
Thank you very much. 
this is very helpful for me, I used to `rm -rf ` before and it wasn't best strategy :D .

Currently, I'm working on next version with separating `parser` and `generator` to be more readable and easier to modify (I know,  current code doesn't look best at all). 

I would love to hear more tips, recommendation or at least some kind of feedback

**Comment by cobraz** [comment]
If you push your changes to a separate branch, I can probably help you out with a few PRs 👍 

PS: If you wanna chat, I'm on [keybase](https://keybase.io/cobraz) now. Hit me up!

**Comment by cobraz** [comment]
I agree, didn't think of that. What do you think? Should that be included in `wsdl-tsclient` or something the users fixes themselves?

**Comment by dderevjanik** [comment]
Well, I tried to look on big projects like [openapi-generator](https://github.com/OpenAPITools/openapi-generator) and they are not removing whole folder, neither specific file. They just overwrite existing ones and letting users to have different files nearby. 

I think it would be best approach to copy `openapi-generator` way and let users to fixes themselves. I don't want to make things different for generating clients.

**Comment by cobraz** [comment]
Okey, so they just have "overwrite enabled" by default?

**Comment by dderevjanik** [comment]
Yes, its turned on by default. 
There's also option for `not to overwrite`, but I think I'm going to leave for now...
