### ISSUE TITLE
Ability to pass `quiet` and `verbose` options to `parseAndGenerate` function.

### ISSUE THREAD

**Issue by dmitryk-sfx** [dderevjanik/wsdl-tsclient#34]
As title say I think need to add ability to pass `quiet` and `verbose` options to `parseAndGenerate` function.

**Comment by dderevjanik** [comment]
Hi,

Added in latest commit, will be released in next few days. Thanks for idea!

**Comment by dmitryk-sfx** [comment]
Big thanks!

**Comment by dmitryk-sfx** [comment]
> Hi,
> 
> Added in latest commit, will be released in next few days. Thanks for idea!

Any news about new release?

**Comment by dderevjanik** [comment]
@dmitryk-sfx `1.4.0` is released
