### ISSUE TITLE
wsdl_options not available in the generated interface methods

### ISSUE THREAD

**Issue by sasan-k** [dderevjanik/wsdl-tsclient#42]
Hi, I started using this lib to generate soap contracts for a nest js project. The generated xxxAsync methods are not accepting wsdl_options in the contracts generated but in the actual soap object they are available. We specifically need the timeout option but would be great if we can access all options. Currently Im able to achieve this by manually changing the generated method and add the second parameter type to accept options but every time we generate we ahve to do this again. could you please make this available? 

we are using   "wsdl-tsclient": "^1.4.0"

**Comment by ZimGil** [comment]
Hi @dderevjanik could this be revisited?
