### ISSUE TITLE
CLI and modelPropertyNaming

### ISSUE THREAD

**Issue by gocjp** [dderevjanik/wsdl-tsclient#89]
Hello,

Is there a way to use modelPropertyNaming with CLI? I went through the code and I'm missing how to use it. Very nice feature which our team would gladly benefit :)

**Comment by dderevjanik** [comment]
Hi @gocjp ,

thanks for creating an issue :) . I just released version `1.7.0` with CLI option `--modelPropertyNaming="camelCase"` (or `"PascalCase"`)
