### ISSUE TITLE
Wrong import path

### ISSUE THREAD

**Issue by stondini** [dderevjanik/wsdl-tsclient#9]
Hello,

It seems the generator produces the import path according to the operating system.
Node is supposed to abstract this point so import should be always like `../../../file` (using slash separator).

Mac (compile):
`import { MyRequest } from "../definitions/MyRequest";`

Windows (doesn't compile):
`import { MyRequest } from "..\definitions\MyRequest";`

What do you think ?

Thank you
Stephane

**Comment by dderevjanik** [comment]
Hello, 

You are right.... Right now, I didn't make `wsdl-tsclient` generator cross-platform, so Windows is probably broken. 
I tried it on Windows with WSDL and everything is working.

But it shouldn't be difficult to make it cross-platform. 
Everything else is working for you on MAC ? I mean, is wsdl-tsclient generating right client with types ?

Thank you !

**Comment by stondini** [comment]
Node is already cross-platform compliant so you don't need to build the path by yourself.

You are using `path` library which is correct to read WSLD and XSL files but not to generate the `import` statements.
Just use "/" in all `import` statements.

**Comment by dderevjanik** [comment]
Ah, yes. I completly forgot that I hardcoded several relative paths import with `/`.
Thank you for report, will try to fix it and release new version ASAP.

**Comment by dderevjanik** [comment]
I released [new version 1.1.0](https://github.com/dderevjanik/wsdl-tsclient/releases/tag/1.1.0) with fix. 
Can you try again, pls ?

**Comment by stondini** [comment]
Hello,
It works like a charm :)
All files are correctly imported and transpiled on Windows NodeJS.

Thank you very much.
